# Generated by Django 5.0.7 on 2024-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashalert',
            name='location',
            field=models.CharField(default='Philippine Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashalert',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
